version: 2.1

orbs:
    node: circleci/node@4.7.0
    browser-tools: circleci/browser-tools@1.4.4

jobs:
    test_player:
        docker:
            - image: cimg/node:18.1.0-browsers
        steps:
            - checkout
            - node/install-packages:
                  pkg-manager: npm
            - browser-tools/install-chrome:
                  chrome-version: 116.0.5845.96 # TODO: remove until: https://github.com/CircleCI-Public/browser-tools-orb/issues/75
                  replace-existing: true # TODO: remove until: https://github.com/CircleCI-Public/browser-tools-orb/issues/75
            - browser-tools/install-chromedriver
            - run:
                  command: |
                      google-chrome --version
                      chromedriver --version
                  name: Check Chrome
            - run:
                  name: Headless Chrome tests
                  command: npm test
            - run:
                  name: Send results to Coverage
                  command: npm run coveralls

workflows:
    end-to-end-tests:
        jobs:
            - test_player
